### ISSUE TITLE
Dimensionar a imagem de fundo

### ISSUE THREAD

**Issue by DrigoCarvalho** [Hoffmano/InsideWhats#8]
A primeira seção tem uma imagem de background, porém ela não se ajusta com o tamanho da tela e está mal dimensionada, quando comparada à versão do AXD

**Comment by DrigoCarvalho** [comment]
No momento a imagem está referenciada dentro do main.css no .secao1, então se tiver forma melhor de colocar como background removam de lá

**Comment by GuilhermeBalog** [comment]
Arrumei!

**Comment by GuilhermeBalog** [comment]
> No momento a imagem está referenciada dentro do main.css no .secao1, então se tiver forma melhor de colocar como background removam de lá

Acho que esta é a melhor forma mesmo
